import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
import html
import re

load_dotenv()


def build_summary_html(summary_text: str) -> str:
    lines = [line.rstrip() for line in summary_text.splitlines()]
    blocks = []

    def normalize_inline(text: str) -> str:
        escaped = html.escape(text)
        escaped = re.sub(r'`([^`]+)`', r'<code style="background:#eef2ff;padding:2px 6px;border-radius:6px;">\1</code>', escaped)
        return escaped

    current_list = []

    def flush_list() -> None:
        nonlocal current_list
        if current_list:
            blocks.append(
                '<ul style="padding-left:20px;margin:6px 0 14px;">'
                + ''.join(f'<li style="margin:6px 0;line-height:1.7;">{item}</li>' for item in current_list)
                + '</ul>'
            )
            current_list = []

    for raw_line in lines:
        line = raw_line.strip()
        if not line:
            flush_list()
            continue

        if line.startswith('**') and line.endswith('**') and len(line) > 4:
            flush_list()
            blocks.append(f'<h2 style="font-size:18px;color:#1d4ed8;margin:20px 0 8px;">{normalize_inline(line.strip("*"))}</h2>')
            continue

        if line.startswith('#'):
            flush_list()
            heading = line.lstrip('#').strip()
            blocks.append(f'<h2 style="font-size:18px;color:#1d4ed8;margin:20px 0 8px;">{normalize_inline(heading)}</h2>')
            continue

        if line.startswith('* '):
            current_list.append(normalize_inline(line[2:]))
            continue

        flush_list()
        blocks.append(f'<p style="margin:8px 0;line-height:1.7;">{normalize_inline(line)}</p>')

    flush_list()

    if not blocks:
        blocks.append('<p style="margin:8px 0;line-height:1.7;">Summary not available.</p>')

    return (
        '<div style="font-family: Arial, sans-serif; max-width: 700px; margin: auto; color: #1f2937; '
        'background:#f9fafb; padding: 32px; border-radius: 12px;">'
        '<h2 style="font-size:18px;color:#1d4ed8;margin:18px 0 6px;">YouTube Summary</h2>'
        + ''.join(blocks)
        + '<hr style="border:none;border-top:1px solid #e5e7eb;margin:28px 0;"/>'
        + '<p style="font-size:12px;color:#6b7280;text-align:center;">Generated by YouTube Summarizer</p>'
        + '</div>'
    )

def send_email(to_email: str, subject: str, content: str):
    """
    Sends an email using Gmail SMTP.
    """
    email_user = os.getenv("EMAIL_USER")
    email_pass = os.getenv("EMAIL_PASS")

    if not email_user or not email_pass:
        raise Exception("SMTP credentials missing from environment.")

    msg = MIMEMultipart()
    msg['From'] = email_user
    msg['To'] = to_email
    msg['Subject'] = subject

    html_content = build_summary_html(content)
    msg.attach(MIMEText(html_content, 'html'))

    try:
        with smtplib.SMTP('smtp.gmail.com', 587) as server:
            server.starttls()
            server.login(email_user, email_pass)
            server.send_message(msg)
    except Exception as e:
        raise Exception(f"Failed to send email: {str(e)}")
